Set up preamble for Slonik

diff --git a/mahout b/mahout
--- a/mahout
+++ b/mahout
@@ -1843,10 +1843,45 @@ function mahout_slonik () {
 
     # What all do we need?
     #   - figure out origin node ID - ORIGINNODEID
+    local ORIGINNODEID
+    QORIGIN="select set_origin from \"_${SLONYCLUSTER}\".sl_set where set_id = ${SLONYMAINSET};"
+    ORIGINNODEID=`psql -d $MAINDATABASE -qAt -c "${QORIGIN}"`
+    rc=$?
+    case ${rc} in
+	0)
+	    glog user.info "Found origin node ID: ${ORIGINNODEID}"
+	    ;;
+	1)
+	    glog user.error "Fatal error finding node origin ID"
+	    exit 1
+	    ;;
+	2)
+	    glog user.error "Error querying node origin ID"
+	    exit 1
+	    ;;
+	3)
+	    glog user.error "Error querying node origin ID"
+	    exit 1
+	    ;;
+    esac
     #   - slony preamble, already gotten earlier
     #      cluster name=$SLONYCLUSTER;
     #        plus per-node
     #      node $nodenum admin conninfo='something'
+    SLONIKPREAMBLE=${PWD}/.mahout-temp/mahout-preamble.slonik
+    echo "
+cluster name=${SLONYCLUSTER};
+" > $SLONIKPREAMBLE
+    QNODES="select sub_provider from \"_${SLONYCLUSTER}\".sl_subscribe where sub_set = $SLONYMAINSET
+                            union select sub_receiver from \"_${SLONYCLUSTER}\".sl_subscribe where sub_set = $SLONYMAINSET;"
+    nodes=`psql -d "${MAINDATABASE}" -qAt -c "${QNODES}" | sort -n`
+    for node in `echo $nodes`; do
+	QPATH="select min(pa_conninfo) from \"_${SLONYCLUSTER}\".sl_path where pa_server=$node;"
+	conninfo=`psql -d "${MAINDATABASE}" -qAt -c "${QPATH}"`
+	echo "node ${node} admin conninfo='${conninfo}';" >> $SLONIKPREAMBLE
+    done
+
+    exit
     #   - set drop table
     #     drop the table from the main set
     #   - run the DDL via EXECUTE SCRIPT
