Sketching out notes for doing slony stuff

diff --git a/mahout b/mahout
--- a/mahout
+++ b/mahout
@@ -1297,8 +1297,6 @@ function mahout_history () {
 
     # Clean up afterwards
     rm -rf ${depfodder} ${dependencies} ${versionorder} ${versioncontent}
-    summary history
-}
 
 function mahout_attach () {
     local PRODVERSION=${PARM1}
@@ -1433,6 +1431,112 @@ function mahout_build () {
     summary build
 }
 
+function mahout_attach () {
+    local PRODVERSION=${PARM1}
+    local CMPDATA
+    # check that we're in a Mahout directory
+    local INMAHOUT
+    local PGCMPOUTPUT
+
+    INMAHOUT=`in_mahout_home`
+    if [[ ${INMAHOUT} != 0 ]]; then
+	glog user.error "attach: not in mahout directory - ${INMAHOUT}"
+	exit 1
+    fi
+    
+    # acquire configuration from mahout.conf
+    read_mahout_config
+    glog user.notice "Attaching version [${PRODVERSION}] changes to database MAINDATABASE=[${MAINDATABASE}]"
+
+    # Verify that the version PRODVERSION matches against a valid
+    # version, e.g. - one where there is a dump found in .mahout-data
+    CMPDATA=${PWD}/.mahout-data/${PRODVERSION}.pgcmp
+    if [[ -e ${CMPDATA} ]]; then
+	glog user.notice "Found comparison data for version - [${CMPDATA}]"
+    else
+	glog user.error "No comparison data found for version [${PRODVERSION}] - [${CMPDATA}]"
+	exit 1
+    fi
+
+    # Need to rummage through the cluster to get all the Database URIs for nodes
+    
+    
+    # Verify that every database does NOT have Mahout installed, e.g. -
+    # no Mahout schema
+    query="select count(1) from pg_catalog.pg_namespace where nspname = '${MAHOUTSCHEMA}';"
+    scount=`psql -d ${MAINDATABASE} -c "${query}" -qAt`
+    if [[ ${scount} != 0 ]]; then
+	glog user.error "attach: main database already has ${MAHOUTSCHEMA} schema - apparently already mahout-ized"
+	exit 1
+    fi
+   
+    # Most likely needs to have a pgcmp "expected differences" file to
+    # indicate what differences are acceptable; need to be quite
+    # strict about this!
+
+    # run pgcmp to see differences versus the specified version
+    # any unexpected differences lead to failing the install
+    LABEL="production-${PRODVERSION}"
+    CAPTUREFILE=${PWD}/.mahout-temp/attach-${PRODVERSION}.pgcmp
+    dump_current_schema "${LABEL}" ${CAPTUREFILE}
+
+    # Now, run pgcmp against the two schemas:
+    PGCMPWORK=`mktemp -d /tmp/mahout-attach-pgcmp-work.XXXXXXXXXXX`
+    PGBINDIR=${PGBINDIR} PGCLABEL1="${LABEL}" PGCLABEL2=${PRODVERSION} PGURI=${COMPARISONDATABASE} PGCOMITSCHEMAS=${MAHOUTOMITSCHEMAS} PGCMPINPUT1=${CAPTUREFILE} PGCMPINPUT2=.mahout-data/${PRODVERSION}.pgcmp PGCWORKDIR=${PGCMPWORK}  ${PGCMPHOME}/pgcmp
+    rc=$?
+    case ${rc} in
+	0)
+	    glog user.notice "pgcmp found exact match"
+	    rm -rf ${PGCMPWORK}
+	    ;;
+	2)
+	    glog user.error "pgcmp failed to run properly - see ${PGCMPWORK}/perform-comparison.log"
+	    exit 1
+	    ;;
+	3)
+	    glog user.error "pgcmp found differences inadequately explained - see ${PGCMPWORK}/perform-comparison.log"
+	    exit 2
+	    ;;
+    esac
+
+    # But if there are no differences, then we need to add mahout
+    # schema as is added by mahout install/init, and indicate
+    # that it was marked as OK with the specified version
+    local SETUPQ=`mktemp /tmp/mahout-attach-setup.XXXXXXXXXXXXXX`
+    mahout_initialize_schema > ${SETUPQ}
+    echo " insert into action_log (action_start, action_end, action, version, action_type, action_source, result, success) values (now(), now(), 'attach mahout', '${PRODVERSION}', 'attach', 'mahout', 'initialized', 't');
+    insert into version_log (version, install_start, install_end) values ('${PRODVERSION}', now(), clock_timestamp());
+  commit;" >> ${SETUPQ}
+
+    psql -d ${MAINDATABASE} -f ${SETUPQ} > /dev/null 2>&1
+    retcode=$?
+    if [ $retcode -ne 0 ]; then
+	glog user.error "Unable to setup mahout schema ${MAHOUTSCHEMA} in database [${MAINDATABASE}]"
+	exit 1
+    else
+	glog user.notice "Setup mahout schema ${MAHOUTSCHEMA} in database [${MAINDATABASE}]"
+	rm -f ${SETUPQ}
+    fi
+    glog user.notice "mahout attach completed for version [${PRODVERSION}] in database [${MAINDATABASE}]"
+    summary attach
+}
+
+### Overview...
+### - hygiene checks, that Mahout is in good shape
+### - verify that DB node is the origin
+### - pull list of other nodes
+### - iterate through nodes, verifying
+###   - Version matches
+###   - dump schema via pgcmp, verify that each node matches the mahout-provided data
+###   - Get shape of cluster
+###   - calculate dependencies (of dependencies in Mahout)
+###   - for each version being upgraded
+###     - get ddl requests, drop into Slonik script
+###     - determine the tables to be added, generating SET ADD TABLE
+###     - determine the sequences to be added, generating SET ADD SEQUENCE
+###     - determine the tables to be dropped, generating SET DROP TABLE
+###     - determine the sequences to be dropped, generating SET DROP SEQUENCE
+###     - something up with ddl vs psql vs ddl-autocommit vs superuser
 function mahout_slonik () {
     # starts similarly to mahout_upgrade, checking hygiene
     
@@ -1510,20 +1614,20 @@ function mahout_slonik () {
 		    if [[ $(echo ${line} | egrep -c "^requires ") -eq 1 ]]; then
   		        echo "no action apropos for requires line"
 		    fi
-		    if [[ $(echo ${line} | egrep -c "^psql ") -eq 1 ]]; then
+		    if [[ $(echo ${line} | egrep -c "^ddl ") -eq 1 ]]; then
 			local sqlscript=`echo ${line} | cut -d " " -f 2`
-			glog user.notice "apply SQL Script ${sqlscript}"
+			glog user.notice "apply DDL Script ${sqlscript}"
 			md5sum=`md5sum < ${sqlscript}`
 			cat ${sqlscript} | md5sum > ${sqlscript}.md5sum
-			action_start $propversion slonik "psql script" ${sqlscript} "${md5sum}"
+			action_start $propversion slonik "DDL script" ${sqlscript} "${md5sum}"
 			psql -d ${MAINDATABASE} -f ${sqlscript} --variable ON_ERROR_STOP=1 --single-transaction > ${sqlscript}.${propversion}.log 2>&1
 			retcode=$?
 			if [ $retcode -ne 0 ]; then
-			    glog user.error "psql script ${sqlscript} failed against database [${MDB}]"
-			    action_end "slonik" "psql script" "${sqlscript}" "${md5sum}" f
+			    glog user.error "DDL script ${sqlscript} failed against database [${MDB}]"
+			    action_end "slonik" "DDL script" "${sqlscript}" "${md5sum}" f
 			    exit 1
 			else
-			    action_end ${propversion} "slonik" "psql script" "${sqlscript}" "${md5sum}" t
+			    action_end ${propversion} "slonik" "DDL script" "${sqlscript}" "${md5sum}" t
 			fi
 		    fi
 		    if [[ $(echo ${line} | egrep -c "^superuser ") -eq 1 ]]; then
@@ -1600,6 +1704,9 @@ case $SUBCOMMAND in
        ;;
    slonik)
        mahout_slonik
+       ;;
+   slony_attach)
+       mahout_slony_attach
        ;;
    history)
        mahout_history
