Implemented dependency checking in validation step

diff --git a/mahout b/mahout
--- a/mahout
+++ b/mahout
@@ -58,7 +58,7 @@ function glog () {
 	user.warning)
 	    WARNINGS=$((${WARNINGS} + 1))
 	    ;;
-	user.err)
+	user.error)
 	    PROBLEMS=$((${PROBLEMS} + 1))
 	    ;;
     esac	    
@@ -80,7 +80,7 @@ function mahout_init () {
     PGCH=${PGCMPHOME:-"/home/cbbrowne/PostgreSQL/pgcmp"}
 
     if [ -d $MAHOUTHOME ]; then
-	glog user.err "Directory [${MAHOUTHOME}] already exists - aborting"
+	glog user.error "Directory [${MAHOUTHOME}] already exists - aborting"
 	exit 1
     else
 	mkdir $MAHOUTHOME 
@@ -112,7 +112,7 @@ function mahout_init () {
 	if [ -x ${PGCH}/${pgm} ]; then
 	    glog user.notice "found ${PGCH}/${pgm} executable OK"
 	else
-	    glog user.err "did not find executable ${PGCH}/${pgm}"
+	    glog user.error "did not find executable ${PGCH}/${pgm}"
 	fi
     done
     echo "# Add additional configuration parameters for scripts after this" >> ${MO}
@@ -122,7 +122,7 @@ function mahout_init () {
     
     MAHOUTCAP=${MAHOUTHOME}/.mahout-data
     if [ -d ${MAHOUTCAP} ]; then
-	glog user.err "Capture directory MAHOUTCAP [${MAHOUTCAP}] already exists"
+	glog user.error "Capture directory MAHOUTCAP [${MAHOUTCAP}] already exists"
 	exit 1
     else
 	mkdir ${MAHOUTCAP}
@@ -133,7 +133,7 @@ function mahout_init () {
     
     MAHOUTCTL=${MAHOUTHOME}/mahout.control
     if [ -e ${MAHOUTCTL} ]; then
-	glog user.err "Control file MAHOUTCTL=[${MAHOUTCTL}] already exists"
+	glog user.error "Control file MAHOUTCTL=[${MAHOUTCTL}] already exists"
     else
 	echo "# Initialized mahout.control" > ${MAHOUTCTL}
 	echo "# add sections after this to indicate versions" >> ${MAHOUTCTL}
@@ -170,7 +170,7 @@ function mahout_init () {
     psql -d ${MDB} -f ${MAHOUTTMP}/setup-mahout-schema.sql > /dev/null 2>&1
     retcode=$?
     if [ $retcode -ne 0 ]; then
-	glog user.err "Unable to setup mahout schema in database [${MDB}]"
+	glog user.error "Unable to setup mahout schema in database [${MDB}]"
 	exit 1
     else
 	glog user.notice "Setup mahout schema in database [${MDB}]"
@@ -186,7 +186,7 @@ function mahout_init () {
     PGCLABEL=Base PGURI=${MDB} PGCOMITSCHEMAS=${MAHOUTOMITSCHEMAS} PGCMPOUTPUT=${BASEPGCMP} ${PGCH}/pgcmp-dump > /dev/null
     rc=$?
     if [ $rc -ne 0 ]; then
-	glog user.err "Failure to use pgcmp to dump base schema - rc=[${rc}]"
+	glog user.error "Failure to use pgcmp to dump base schema - rc=[${rc}]"
     else
 	glog user.notice "Dumped Base schema pgcmp data to ${BASEPGCMP}"
     fi
@@ -198,9 +198,9 @@ function mahout_init () {
 #   [DO STUFF]
 #   then release the lock by changing LOCKED to false, then trim
 
-function mahout_validate_control () {
+function validate_control () {
     local CTL=${PWD}/mahout.control
-    glog user.notice "mahout validate_control: validating control file [${CTL}]"
+    glog user.notice "validate_control: validating control file [${CTL}]"
     if [ -e ${CTL} ]; then
 	glog user.notice "Found [${CTL}]"
 	local dropcomments=`mktemp /tmp/mahout-ctl-check.sanscomments.XXXXXXXXXXX`
@@ -214,7 +214,7 @@ function mahout_validate_control () {
 	egrep -n -v "^(version|psql|common tests|psqltest|requires|superuser|shell)[ ]*" ${dropwhitespace} | egrep -v "^[0-9]+:$" > ${badlines}
 	NUMBAD=`cat ${badlines} | wc -l`
 	if [[ ${NUMBAD} -gt 0 ]]; then
-	    glog user.err "Found ${NUMBAD} ill-formatted lines"
+	    glog user.error "Found ${NUMBAD} ill-formatted lines"
 	    cat ${badlines}
 	    exit 1
 	fi
@@ -228,7 +228,7 @@ function mahout_validate_control () {
 	    if [ -e ${pfilename} ]; then
 		glog user.notice "psql file ${pfilename} on line ${lineno} exists"
 	    else
-		glog user.err "psql file ${pfilename} on line ${lineno} does not exist"
+		glog user.error "psql file ${pfilename} on line ${lineno} does not exist"
 	    fi
 	done < ${psqlscripts}
 
@@ -242,7 +242,7 @@ function mahout_validate_control () {
 	    if [ -e ${pfilename} ]; then
 		glog user.notice "shell file ${pfilename} on line ${lineno} exists"
 	    else
-		glog user.err "shell file ${pfilename} on line ${lineno} does not exist"
+		glog user.error "shell file ${pfilename} on line ${lineno} does not exist"
 	    fi
 	done < ${shellscripts}
 	
@@ -260,18 +260,50 @@ function mahout_validate_control () {
 	    if [ "${requiredver}" != "" ]; then
 		glog user.notice "Line ${lineno} wants version ${required}, found as ${requiredver}"
 	    else
-		glog user.err "Line ${lineno} wants version ${required}, not found"
+		glog user.error "Line ${lineno} wants version ${required}, not found"
 	    fi
 	done < ${rfile}
 	
 	# check that there are no loops
 	# Assemble dependencies, run through tsort
+	local depfodder=`mktemp /tmp/mahout-ctl-check-dependency-fodder.XXXXXXXXXXXX`
+	local dependencies=`mktemp /tmp/mahout-ctl-check-dependencies.XXXXXXXXXXXX`
+	egrep -n "^(version|requires)" ${dropwhitespace} > ${depfodder}
+	local dversion
+	local drequires
+	while read line
+	do
+	    if [ $(echo "${line}" | egrep -c "^[0-9]+:version") -eq 1 ]; then
+		dversion=`echo ${line} | cut -d : -f 2 | sed "s/^version //"`
+		echo "found version: ${dversion}"
+	    fi
+	    if [ $(echo "${line}" | egrep -c "^[0-9]+:requires") -eq 1 ]; then
+		drequires=`echo ${line} | cut -d : -f 2 | sed "s/^requires[ \t]//"`
+		echo "${drequires} ${dversion}" >> ${dependencies}
+		echo "found requires: ${drequires}"
+	    fi
+	done < ${depfodder}
+	glog user.notice "Generated dependency list: ${dependencies}"
+	local versionorder=`mktemp /tmp/mahout-ctl-check-versionorder.XXXXXXXXXXXX`
+	tsort ${dependencies} > ${versionorder}
+	retcode=$?
+	if [ $retcode -ne 0 ]; then
+	    glog user.error "Dependency cycle found - see [${dependencies}]"
+	else
+	    glog user.notice "Dependencies checked, no cycles found OK"
+#	    rm ${dependencies}
+	fi
 	
-	rm -f ${shortened} ${dropcomments} ${dropwhitespace} ${badlines} ${psqlscripts} ${badlines} ${vfile} ${rfile} ${shellscripts}
-			    
+	rm -f ${shortened} ${dropcomments} ${dropwhitespace} ${badlines} ${psqlscripts} ${badlines} ${vfile} ${rfile} ${shellscripts} ${depfodder} ${versionorder}
     else
-	glog user.err "Control file [${CTL}] not found"
+	glog user.error "Control file [${CTL}] not found"
 	exit 1
+    fi
+    if [ $PROBLEMS -gt 0 ]; then
+	echo "Problems found - error count: ${PROBLEMS}"
+	exit 1
+    else
+	exit 0
     fi
 }
 
@@ -353,7 +385,7 @@ case $SUBCOMMAND in
        mahout_changes
        ;;
    validate_control)
-       mahout_validate_control
+       validate_control
        ;;
    *)
        echo "Invalid subcommand - [${COMMAND}]"
